# VIM
alias "vimt"="vim -c 'NERDTree'"

# TMUX

# GITHUB
alias "commat"="git add -A; git commit"
alias "push"="git push"

# Compiling
# GDB
alias "gdbc"="gcc -g3 -Wall -Wextra -o"
alias "gdbui"="gdb -tui"

# Python
alias "pythonc"="python3 -m py_compile"

