# VIM
alias "vimt"="vim -c 'NERDTree'"

# TMUX

# GITHUB
alias "commat"="git add -A; git commit"
alias "push"="git push"

# Compiling && GDB
alias "gdbc"="gcc -g3 -Wall -Wextra"
alias "gdbui"="gdb -tui"
alias "jk"="<Esc>"

